#!/bin/sh

set -eu

if [ "$(git status --porcelain .)" != "" ]; then
    echo "Dirty git"
    exit 1
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then
    echo "Bad branch"
    exit 1
fi

git fetch
git push origin master:master

git tag --sort=committerdate --list 'v[0-9]*'

echo "New version without the 'v'"
read -p "version> " version

git push origin HEAD:release/v${version}