#!/bin/sh

set -eu

if [ "$(git status --porcelain .)" != "" ]; then
    echo "Dirty git"
    exit 1
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then
    echo "Bad branch"
    exit 1
fi

git push origin master:master

git tag


read -p "New version without the 'v'>" version

git tag -a "v$version" -m "v$version"
git push
git push --tags