#!/bin/sh

set -eu

if [ "$(git status --porcelain .)" != "" ]; then
    echo "Dirty git"
    exit 1
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then
    echo "Bad branch"
    exit 1
fi

git push origin master:master

git tag


echo "New version without the 'v'"
read -p "version> " version

git tag -a "v$version" -m "$version"
git push
git push --tags