on: [push]

name: CI

jobs:
    build_and_test:
        name: Rust project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Use Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  target: x86_64-unknown-linux-musl
                  toolchain: stable
                  override: true

            - name: Run cargo test
              run: |
                  cargo test
